### ISSUE TITLE
error using janitor

### ISSUE THREAD

**Issue by johnrakestraw** [pprevos/denote-explore#22] opened 2024-07-25 19:04 UTC
This is a really great enhancement to denote. Thanks.

I'm confident this is user error, but I'm hoping you can give me a hint on how to fix it. Whenever I execute <denote-explore-sort-keywords> or <denote-explore-sync-metadata> the immediate response in the mini-buffer is "the destination file [filename with complete path] already exists. In both instances it's choking on the same file. If I remove that file, then both functions choke on another file, but still the same one in both instances. 

Any hints for what I should check?

**Comment by pprevos** [comment] 2024-07-25 20:30
Hi John,

Which function are you using?

**Comment by johnrakestraw** [comment] 2024-07-25 20:41
Thanks for the prompt response, and apologies -- I was sure that I included the two functions, but it seems that I deleted them when re-editing the post. 

I get this response with <denote-explore-sort-keywords> and <denote-explore-sync-metadata>

**Comment by johnrakestraw** [comment] 2024-07-25 20:42
Ah -- I see. It seems that this site  deletes terms when they're enclosed in angle brackets.

The two functions -- denote-explore-sync-metadata and denote-explore-sort-keywords

**Comment by pprevos** [comment] 2024-07-25 23:58
GitHub uses Markdown. Use backticks for code: e.g. `denote-explore-sync-metadata`.

Looks like these are caused by the recent updates in Denote version 3. I will need to review this over the weekend and rewrite these functions.

**Comment by johnrakestraw** [comment] 2024-07-26 01:02
Thanks for the tip about github's markdown. And for the code development. (And, as long as I'm here, for the emacs writing studio!)

--John

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by pprevos** [comment] 2024-07-27 06:25
I just committed a new version. I tested all functionality for compatability with Denote 3.0. Thanks for notifying me.

Feel free to provide more feedback to further improve this package.

**Closed as completed by pprevos** 2024-07-27 06:25 UTC

**Comment by johnrakestraw** [comment] 2024-07-27 13:41
I've upgraded, and I can confirm the fix. Thanks for the prompt response.

--John

Sent with [Proton Mail](https://proton.me/) secure email.
